# Modes of reproduction, barriers, genetic variation and hybridization techniques

## Modes of reproduction

### Gametophyte

- Fertilization requires Nicking to occur.
- Perfect, complete, monoecious/dioecious flower types.
- Male gametophyte:
  - Each anther is bilobed (has two pollen sacs)
  - Pollen sac (microsporangium) is filled with number of large sized cells called sporogenous cells or microsporocytes.
  - Microsporocytes produce microspore mother cells by mitotic division.
  - Microspore mother cell or pollen mother cells undergo meiotic division to produce microspores at the end of second division.
  - Anther contains exine, intine, generative nucleus and vegetative nucleus.
- Female gametophyte:
  - Within ovary, starts as small outgrowth (tiny knob) within nucellus.
  - Nucellus is multilayered main body of ovule which encloses one or two protective layers called integuments, except for a small pore at one end. Integuments are outer and inner, outer layer eventually becomes testa.
  - Developing ovule attached to placenta by funiculus, scar called hilium forms after detachment.
  
**Agents of pollination**

- Wind/anemophily: Maize, oats, coconut palm, cannabis, etc.
- Water/hydrophily: Hydrilla, zostera marina, etc.
- Insect/entomophily: Mustard
- Bird/ornithophily: Red silk cotton, bottle brush, etc.
- Bat pollination/chiropterophily: Adansonia

**Endosperm development**

## Genetic variation: importance and approaches for its improvement in crop breeding

$\longrightarrow$ Breeding objectives are realized by combining the favorable genes of different sources (parents). That is, one cannot breed, for example, disease resistance if the gene conferring resistance of disease of interest does not occur in the base population.

As genetic variation is heritable and results in permanent change in phenotype (trait) of organism, it is the variability of interest of breeder, since breeder can predictably control it through selection. Moreover, genetic variation is detectable at molecular as well as gross morphological level but the variation due to environment cannot be. It is also possible for the source of variation to be channeled through carefully designed mating system.

Primarily there are 3 types of sources of genetic variability:
  1. Gene recombination
  2. Modification of chromosome number
  3. Mutation
  
Plant breeder can increase genetic variability by use of following tools:

1. Hybridization: Crossing un-identical plants to transfer genes or achieve recombination (creating non-parental type through physical exchange of chromosomal segments). In hybridization, effects of segregation and indepenent assortment in crosses between individual heterozygous for given number of gene pairs is evident. If we take 2 alleles for any 'n' of genes, following indicators of variation can be deduced:

  - Different number of gametes produced by $F_1$ heterozygotes: $2^n$
  - Number of combinations of $F_1 \times F_1$ gametes (perfect population size): $4^n$
  - Different kinds of genotypes in $F_2$ = $3^n$
  - Different kinds of $F_2$ genetypes that are homozygous: $2^n$
  - Different kinds of $F_2$ genotypes that are heterozyous: $3^n-2^n$
  - Different types of phenotypes in $F_2$ (complete dominance): $2^n$
  

2. Wide crossing: Crossing of distantly related individuals for desirable gene introgression. Generally wild relatives of native agricultural crops contain such genes for biotic and abiotic stress tolerance. For example in tomato breeding, program resistance to Oidium neolycopersici (powdery mildew of tomato) monogenic resistance was found in _S peruvianum_ accession, _S habrochaites_ accession and polygenic resistance in _S neorikii_ accessions.

Both of these breeding methods depend upon the number of allele variants per loci. In a gene system involving two alleles, 3 genetic variants (genotypes) are possible, while for a triallelic system 6 individuals may arise from hybridization.

3. Polyploidization: It is accomplished through chromosome doubling, which can occur naturally (through modification of chromosome number as a result of hybridization or abnormalities in nuclear division process) or can be induced using spindle disrupter Colchicine. 

4. Mutagenesis: Also known as ultimate source of biological variation, mutation may arise spontaneously in nature of as a result of errors in cellular process such as DNA replication (or duplication) and by chromosomal abberations (deletion, duplication, inversion and translocation). Mutations may too be induced artificially by using mutagenic agents: irradiation and chemicals. Commonly occuring mutations are those for dwarfing and nutritional quality. However, most mutations being deleterious in nature are selected against. Although, recessive mutations may remain hidden until much later, when they are expressed in homozygous combination.

## Barriers to crossing and enforcing self and cross pollination enforcing mechanisms

Q. What are the different factors that affect the amount of natural crossing or selfing ? Explain about the mechanisms that enforce self and cross pollination in field crops.

$\longrightarrow$ Species differ in the degrees to which they self pollinate or cross pollinate. Mechanisms promoting self pollination or autogamy are:

1. Cliestomgamy (flowers fail to open), or flowers open only after pollination (chasmogamy)
2. Close proximity of anthers to stigma

Mechanisms that prevent autogamy:

1. Self-incompatibility: In spite of viable and normal pollen and ovule development pollen from a flower is non receptive on the stigma of the same flower, hence incapable of setting seed. This mechanism of reproduction control is conditioned by a single locus "S" with multiple alleles. There are two main type of self incompatibility systems:

  - Heteromorphic: Differences in lengths of stamen and style (heterostyly).
  - Homomorphic:
    1. Gametophytic incompatibility: Ability of the pollen to function is determined by its own genotype and not the plant that produces it.
    2. Sporophytic incompatibility: Incompatibility character of pollen are determined by plant (sporophyte) that produces it.
    
    The self incompatibility mechanism promotes heterozygosity.
    
2. Male sterility: Anther or pollen are non-functional.
  1. Genetic (nuclear/genic): Barley, cotton, soybean, tomato, potato, etc. The system is under control of "ms" gene.
  2. Cytoplasmic male sterility: Controlled by mitochondrial gene. Transmitted only through maternal line.
  3. Cytoplasmic genetic male sterility: Presence of "Rf" gene (nuclear) that overcomes cytoplasmic MS.

3. Dichogamy: Maturing of pistils and stamens of a flower at differnt times. Reduces intensity of self pollination and fertilization. It includes protandry and protogyny.

Factors that affect cross and self pollination are:

1. Environment: 
  - Pollinators: Wind, water, insect, animals (Anemophily, hydrophily, entomophily, zoophily)
  - Temperature: High temperature or low temperature may temporarily overcome SI
  - Light: It induces pollen inviable.
2. Flower appearance: Shape of petal, color radiance, size of flower, olfactory cues, chemical signaling, etc.

### Gene action and methods of breeding

- Self pollinated species: When additive gene action predominates in a self-pollinated species, breeders should consider using selection methods such as pure line selection, mass selection, progeny selection and hybridization. However, when non-additive gene action predominates, effective methods of breeding are the exploitation of heterosis in breeding hybrid cultivars.

- Cross pollinated species: When additive gene action predominates in a cross-pollinated species, recurrent selection may be used to achieve general combining ability (GCA). Specific breeding products to pursue include synthetic varieties and composites. In the case of non-additive gene action, heterosis breeding just like in self pollinated species is recommended for breeding hybrid cultivars. Alternatively, breeders may consider recurrent selection for specific combining ability (SCA) for poulation improvement. Where both additive and non-additive gene action occur together, reciprocal recurrent selection may be used for population improvement.

## Hybridization techniques

### Synthetic cultivar and its development

A synthetic cultivar is a result of open pollinated population improvement, although a synthetic cultivar cannot be propagated without changing the genetic make-up of the population.

A synthetic cultivar must be reconstructed from its parental lines or clones. In case of maize, synthetic cultivars are developed using inbred lines as a three-stage process;
1. Develop a number of inbred lines
2. Progeny test the inbred lines for GCA
3. Identify the 'best' parent and intercross these to produce the synthetic cultivar

The process is almost identical to procedure for developing hybrid cultivars, and only differs in the last stage where many more parents will be included in a synthetic population development than in development of hybrid.

In developing synthetics from clonal selections, following procedure is followed;
1. Establishment of clonal nursery
2. Selection of phenotypically best clones
3. Randomized mating trial
4. Evaluation of progeny to determine genotypically best clones
5. Select parents in synthetic.

In the 4th stage, a test cross or polycross technique will be used to genetically test the best clones identified from colonal screen. The aim of this genetic test is to determine the general combining ability of each clonal line in cross-combinations with other genotypes in the selected group of clones.

If a test cross (often called a 'top cross') is used, all the selected clones are hybridized to one (or more test parent). The test parent will have been chosen because it is a desirable cultivar or it may be chosen because of past experience of the individual breeder. The test parent is a heterozygous clone that produces gametes of diverse genotypes. This diversity of gametes produced from the tester will help an assessment of the average ability of each clone to produce superior progeny when combined with alleles from many different individuals.
