# Germplasm introduction, conservation, utilization, acclimatization and regulation

## Germplasm introduction

### Plant export and import

Plant germplasm can be moved in the form of as true seed, in vitro cultures or vegetative material. True seed is the best material to be transported, as they pose minimum threat with pests and diseases. In vitro material must undergo quarantine procedures. Such quarantine procedures must be amply documented as germplasm health statement.

The import of germplasm needs to complete the following formalities:

- Make a formal request to donor organization/country through NPPO (National Plant Protection Organization).
- Generate import conditions through Pest Risk Analysis (PRA).
- NPPO or the organization responsible to screen the plant material at the port of entry shall inform the donor country (through the institute importing the material) the utility of the material being imported.
- The donor country NPPO evaluates conditions of the importing country and confirms compliance of norms.
- If import conditions are met, NPPO of the donor country prepares a phytosanitary certificate.
- The recipient country issues a Plant Import Permit (PIP). While importing a material, PIP and phytosanitary certificate of the donor country must accompany the material.
- Materials with "Q label" are subjected to quarantine formalities.
- There are countries that do not allow transgenic material. If allowed, such materials are subjected for the verification of the National Biosafety Committee.
- Plant breeders' rights are to be protected while importing any material.
- If the material is imported for cultivation directly, then such materials must undergo formalities of variety release system.

The export of germplasm needs to complete the following formalities:

- The donor country provides import conditions of recipient country.
- Some species that are restricted from export are protected plant varieties as per CITES (Convention on International Trade in Endangered Species of Wild Fauna and Flora, Geneva).
- NPPO (National Plant Protection Organization) of the donor country verifies compliance to the import conditions and prepare phytosanitary certificates.
- Under exceptional circumstances, Material Transfer Agreement (MTA) may be required between exporting and importing institutions.

### Germplasm resources of Nepal

- About 30,000 landraces of 250 cultivated crops.
- Indigenous crops and their landraces have significant contribution to overall food secure being of rural Nepal, globally recognized landraces include "Bhate Phaper" of tartary buckwheat, "Jumli Marshi" and "Anadi" of rice and "Akabare" of chili pepper. 
- Only about 20% of notified germplasm in Nepal have origin in the country itself.
- Pedigree analysis reveals that 13 landraces originated in 8 different countries were used to develop Khumal-4 rice variety.
- A total of 47 ancestors (landraces) originated in 12 different countries were used to develop 20 mid and high hill rice cultivars and a total of 35 ancestors originated in 11 different countries were used to develop 28 rice cultivars for terai region by 2016.

```{r landraces-unique-features}
landraces <- tribble(~"Crop", ~"Local name", ~"Unique character", 
        "Buckwheat", "Bhate pahper", "Loose husk", 
        "Buckwheat", "Kagpani phaper", "Highest rutin content", 
        "Cauliflower", "Garve cauli", "Very large head, perinniality gene, vegetatively propagated", 
        "Chilly" ,"Akabare khursani", "Medicinal value, very spicy and does cause inflammatory of stomach", 
        "Chilly", "Jire khursani", "All year round fruiting", 
        "Finger millet", "Dailekh local", "Higher yielder and adapted to low fertility soils", 
        "Maize", "Pani makkia", "Tolerant to water logged conditions", 
        "Sarsoon", "Gorlikharka", "Highest oil content", 
        "Wheat", "Dabdabe local", "For low fertility and moisture deficient land")

readxl::read_xlsx("./data/rice_varieties_unique_characters.xlsx") %>% 
  mutate(Crop = "Rice") %>% 
  select(-SN) %>% 
  rename(`Local name` = Genotypes) %>% 
  relocate(Crop, .before = 1) %>%
  full_join(landraces, by = c("Crop", "Local name", "Unique character")) %>% 
  arrange(Crop, `Local name`) %>% 
  kableExtra::kbl(booktabs = TRUE, caption = "Some landraces of cultivated crop unique to Nepal", format = "latex", align = "l", longtable = TRUE) %>%
  kableExtra::kable_styling(font_size = 8, repeat_header_continued = TRUE) %>% # do not use use latex_options = "striped" together with collapse_rows, it has unintended results.
  kableExtra::column_spec(column = 2:3, width = c("10em", "18em")) %>% # specifying width for the column that is being collapsed! in a single column_spec statement produces latex error!
  kableExtra::column_spec(column = 1, width = "8em") %>% # interestingly, specifying a separate column_spec for the row that is being collapsed works well. also collapsing a row with long cell contents borks the vertical alignment (valign). so for long texts/labels better stack the row_group_label_position.
  kableExtra::collapse_rows(columns = 1, latex_hline = "full", valign = "middle")

```


## Germplasm collection

Collecting and organizing genetic diversity as a conservation strategy emerged in the 1960s and now plays an important role in ensuring the world's collective food security. Seed saving organizations have helped secure over 100,000 seeds during wartime in Syria, preserve 13 million seeds from over 70 species of native trees in the United Kingdom, and contribute to over US$77 million in pastoral agriculture revenue in New Zealand. As the climate crisis continues, seed preservation may also be critical in research and innovation to help farmers adapt to changing conditions.

According to FAO, there are more than 1,750 ex situ seed banks across the world–both international and local–that preserve over 7 million samples of seeds, cuttings, or genetic material. Following comprise a subset list of selected seed saving organizations working to promote seed diversity through seed banks, exchange networks, and educational programs.

- ASEED Europe, Netherlands
- Australian PlantBank
- Cherokee National Seed Bank, United States
- Crop Trust, Germany: Through its Crop Diversity Endowment Fund, the Crop Trust funds the world’s largest genebanks, including the Consultative Group for International Agriculture Research (CGIAR) genebank platform, Svalbard Global Seed Vault, and Seeds for Resilience–a project supporting five seed banks in Sub-Saharan Africa. 
- Federal Research Center All-Russian Institute of Plant Genetic Resources/VIR, Russia
- Hawai'i Public Seed Initiative, United States
- International Center for Tropical Agriculture (CIAT), Columbia
- Millennium Seed Bank at Wakehurst, England
- SeedChange, Canada
- Svalbard Global Seed Vault, Norway
- The Germplasm Bank of Wild Species, China
- The World Vegetable Center, Taiwan
- Vrihi, India: "Vrihi" is the Sanskrit word for "rice".

## Germplasm conservation

### Importance

(a) Preservation of genetic diversity of various strains and species is conservation. Such preserved accessions can be used in the future.
(b) The valuable genetic traits present in primitive plants will be lost unless such endangered types are conserved.
(c) In clonally multiplied species, the seeds are not feasible material to be conserved due to genetic heterogeneity. In this case, their genes are to be conserved.
(d) The preservation of roots and tubers is difficult because they lose viability. Also, they require larger space. Also, GMOs may be unstable. Such accessions are to be conserved carefully following special techniques.

### Types

#### In-situ conservation

In situ conservation of germplasm is conserving species in their natural environment through establishing biosphere reserves (or national parks/gene sanctuaries). This is accomplished by preserving land plants near natural habitat along with several wild relatives with genetic diversity. The in situ conservation is considered as a high-priority germplasm preservation programme. The limitations are as follows:
a. environmental hazards may endanger the preservations and
b. the cost of maintenance is very high.

#### Ex-situ conservation

Otherwise known as gene banking, this is a method for the preservation of both cultivated and wild. There are two types of gene banking: in vivo and in vitro. While in vivo gene banks preserve seeds, vegetative propagules, etc., in vitro gene banks preserve cell and tissues. For this, knowledge of sampling, regeneration, maintenance of gene pools, etc. are essential. The limitations are as follows:
a. viability of seeds is reduced or lost with passage of time;
b. seeds are susceptible to insect or pathogen attack, often leading to their destruction;
c. this approach is exclusively confined to seed propagating plants, and therefore, it is of no use for vegetatively propagated plants, e.g. potato, Ipomoea and Dioscorea; and
d. it is difficult to maintain clones through seed conservation.

### In-vitro germplasm preservation (Methods for Ex-situ conservation)

1. Germplasm can be preserved in vitro through cryopreservation, low-pressure storage and low-oxygen storage. In cryopreservation, the cells are preserved in a frozen state using solid carbon dioxide (at -79 C), low temperature deep freezers (at -80 C), vapour phase nitrogen (at -150 C) and liquid nitrogen (at -196 C).
Cells stay in completely inactive state. So, they can be conserved for long periods. Tissues like meristems, embryos, endosperms, ovules, seeds, cultured plant cells, protoplasts and callus are usually used for cryopreservation. Cryoprotectants are to be added during cryopreservation. They are DMSO (dimethyl sulfoxide), glycerol, ethylene, propylene, sucrose, mannose, glucose, etc. The damage caused by freezing and thawing will be prevented by cryoprotectants.

2. Germplasm conservation by cold storage is done at low and non-freezing temperature (1–9 C). Here, only growth of the tissue is slowed down. So, cold storage prevents cryogenic injuries. An example to this method is virus-free strawberry plants that can be preserved at 10 C for about 6 years. Grape plants can be preserved for 15 years at 9 C.

3. In low-pressure and low-oxygen storage, the atmospheric pressure and oxygen concentration are reduced. The lowered partial pressure reduces the in vitro growth of plants. Low oxygen concentration keeps partial pressure of oxygen below 50 mmHg (mmHg is a manometric unit of pressure) which reduces growth. Reduced availability of oxygen leads to reduced photosynthetic activity. This technique can be used in increasing the shelf life of fruits, vegetables and flowers.

### DNA Banks or Gene Banks

Germplasm can also be conserved as DNA segments cloned in a suitable vector like cosmids, plasmids or YACs (yeast artificial chromosomes). This is sophisticated, technically demanding and expensive. Threatened species can thus be conserved. Till date, there are no cases where DNA banks are being used as a replacement to traditional method of conservation. However, due to small sample size, this technique has promising potential for the storage of genetic information.

It has become routine to extract DNA from the nuclei, mitochondria and chloroplasts. Derivatives like as RNA and cDNA are also being extracted. Technologies are available to allow all these to be stored quickly and at low cost in DNA banks as an insurance policy against loss of crop diversity. DNA storage allows genetic material for molecular applications. However, use of DNA in conservation is limited as whole plants cannot be directly reconstituted. The genetic material must be introduced through transgenic means. However, DNA banks have a potential future as new technologies develop day by day.

## GMOs: A debatable issue for Nepal

### Prevailing policies and legislations on GMO regulation

- Under "Development of a commercial and competitive farming system", National Agricultural Policy (2061 BS) briefly mentions about regulation of use of GMOs.
  - The production and use of hybrid seeds and improved breeds shall be encouraged, and the use of genetically-modified organism shall be regulated.
- Agricultural Development Strategy (2072/73-2091/92 BS) while setting forth strategies to deal with rising energy cost (Strategy 160), strengthening research-education-extension linkages (Strategy  307), implementing biodiversity policy (Strategy 348) have following clauses 
  - Increase efficiency of farming systems and their genetic materials
  - Strengthening of gene bank and genetic resource program for the use of Intellectual Property Rights.
  - Agriculture education institutions to play a role in academic research that promotes genetic enhancement and supports applied research through collaborative projects and research grants funded by NARF and other sources.
  - Develop regulation for the research and experimentation of Nepalese Biodiversity and Genetic Resources.
  - Restrict the import, production and use of Genetically Modified Organism (Seed, crops and livestocks) except for research to avoid negative impact on biodiversity, genetic resources, and human health.

- National Seed Policy (2056 BS, 1999 AD) (refer to the Chapter on Seed system in Nepal for a brief discussion of policy arrangements)
- Seed Regulations (2069 BS)
- Definition/explaination, regulation and policy guidelines on utilization of germplasm and genetic resources are largely well described in NAP, 2061 and ABDP, 2063 (refer to section on Germplasm conservation, access and utilization)

### Shortcomings

- GMOs/LMOs not explicitly defined.
- Technologies encompassing generation (rDNA, transgenesis, CRISPR-CAS, etc.) of GMOs/LMOs are not stated.
- Forms and derivatives of GMOs/LMOs that fit into or are different from such are not stated.
- ...

### Way forward

- Experience of other countries in use and regulation of genetically modified organisms should serve as point of reference, thus helping to make informed decisions.
- Biosafety reports should be extensively consulted and evaluated to form the basis for decision on whether or not to to introduce particular GM seeds, and how its controlled use may be permitted.
- Cultivation on GM non-food crops, like cotton, could bridge a safer transition towards adoption of this technology.
- ...

## National policy and legislation on germplasm conservation, access and utilization

### National Agro-biodiversity Policy

National Agro-biodiversity Policy (2063 BS), implemented in light of Nepal's commitment to Convention on Biological Diversity, 1992 and in coherence to National Agricultural Policy, 2061 for conservation, promotion and utilization of biological diversity defines following terms:

- Genetic material (Sum total of functional units of all flora, fauna and microbes existing within Nepal)
- Genetic resources (In-situ and ex-situ conserved genetic material as well as existing and potential forms of such genetic materials)
- In-situ
- Ex-situ
- Biological diversity (Diversity of aerial, terrestrial, acquatic, oceanic and other ecosystems of organisms; individual organism (plant, animal and microbe) components of such systems as well as relationship between such components. Includes species diversity, genetic diversity and ecosystem diversity)
- Agro-biodiversity (...includes abstract components affecting specific aspects of agro-biodiversity and socio-economic and cultural components, enlisted more extensively in Schedule-1)
- Agro-biodiversity register
- Access
- Utilization
- Farming community
- Sharing of benefit
- Equitable distribution
- Traditional knowledge
- Biological safety (Measures and methods in place to safeguard agricultural biodiversity, human, animal and plant health and safety and environmental threats against commercial and research use of infectious organism, Genetically Modified Organism or Living Modified Organism)
- Committee (Agricultural Biodiversity, National Conservation Committee)

Policy statement 3 and 4 are explicit about access, utilization, distribution of benefits derived from utilization, and sustainable conservation and promotion of agricultural biodiversity.

**Policy statement 3**: Judicious and equitable distribution system of benefits derived from access and utilization agricultural genetic resources

- Foreign institutions shall be granted access to agricultural genetic resources given that they have obtained permission from Nepal Government and have agree to perform in accordance to the prescribed terms notwithstanding that access to individuals shall not be granted.
- Permission shall not be required for the scientific studies and research of genetic resources and traditional knowledge at the national level. However, such Prior informed consent (PIC) is required in due regard to concerned organization and farming community.
- Equitable distribution of benefits derived from commercial use, intellectual property rights obligations of traditional and indigenous food and agricultural genetic resources, as well as ITK.
- Single door-system shall be implemented in registering, specification of ownership, access, andd utilization of benefits of food and agricultural genetic resources.

**Policy statement 4**: Sustainable agro-biodiversity conservation and promotion for fostering ecosystem balance

- Special emphasis on agro-biodiversity while appraising(accessing) environmental impact in implementation of development programs.
- Research and scientific study of infectious organisms, GMOs and LMOs (modified for food and agricultural purpose) shall require export and research study permissions.
- Control and prohibition of GMOs and their derivaties that have potential risks for negatively impacting biological diversity, environment and human health.
- Conduct scientific study, research and investigation of pollinators and other organisms providing agro-ecosystem services for deriving benefits from sustainable use of agro-ecosystem services.

**Schedule 1 (Working scope of agro-biodiversity)** enlists agricultural genetic resources as:

- Plant derived genetic resources (including fodder, pasture and tree species constituting inter-related component of farming system)
- Animal genetic resources
- Acquatic genetic resources
- Insect genetic resources
- Micro-organism genetic resources
- Wild relatives of cultivated and domesticated species

### National Agricultural Policy

Policy statement 4.4 on "Conservation, promotion and utilization of natural resources and the environment" of the National Agricultural Policy, 2061 envisions the following regarding conservation of biodiversity, including germplasm resources:

- Arrangement shall be made for gene banks and in-situ conservation shall be encouraged in order to conserve biodiversity. Participatory biodiversity parks shall be established in feasible areas.
- Bio-diversity shall be conserved, promoted and utilized and the agro-forestry system shall be developed in such a way as to improve the condition of degraded forests and natural reservoirs.

## Changing global climatic scenario and importance and direction of germplasm conservation and utilization
