
# Plant breeding organizations and academic institutions

## Agriculture and Forestry University

- Agriculture and Forestry University (AFU) was established in Rampur, Chitwan, Nepal in 2010 as first technical university of country. 
- Aims at producing highly skilled human resources required to work on quality research and development in agriculture. It aims at all round development of agriculture, livestock, aquaculture and forestry which would raise the socio-economic conditions of rural people through quality teaching, research and extension.
- Founded after merging Rampur Campus, Institute of Agriculture and Animal Science (IAAS) and Forestry Campus, Hetauda of the Institute of Forestry of Tribhuvan University of Nepal.

### Academic programs and infrastructures 

- In addition to the existing academic programs, the university has started 4 years B.Sc. Fisheries, M.Sc. in Biotechnology, M.Sc. in Weed Science, M.Sc. Seed technology, M.Sc. Agribusiness Management and Ph.D. programs in Developmental Studies.

- Constituent colleges of AFU affiliation
  - College of Natural Resource Management, Purunchaur Kaski, Pokhara (2016)
  - College of Natural Resource Management, Marin Kapilakot, Sindhuli (2017/18)
  - College of Natural Resource Management, Tikapur, Kailali
  - College of Natural Resource Management, Pakhribas, Dhankuta
  - Other constituent colleges are on pipeline for the establishment of B.Sc. Agriculture and B.Sc. Forestry program. 
- AFU has planned to establish B.Sc. Agri. Engineering, B.Sc. Horticulture and Master in Dairy Technology in the near future.
- The Faculty of Agriculture under AFU has 9 departments, 2 centers consisting more than 50 highly qualified faculty members involved in teaching undergraduate and post graduate courses with the support of a team of (67) administrative and technical staff members.
- Besides the production of quality agriculture manpower, FOA is fully committed towards the research and extension activities.

#### Departments

- Department of Agricultural Economics and Agri-Business Management
- Department of Soil Science and Agri-Engineering
- Department of Genetics and Plant Breeding
- Department of Plant Pathology
- Department of Entomology
- Department of Horticulture
- Department of Agriculture Extension and Rural Sociology
- Department of Agricultural Botany and Agri-Ecology
- Department of Agronomy

#### Centers

- Center for Development Studies and Rural Sociology
- Center for Biotechnology

### Research and extension organogram and programs

- Agriculture Science Center (ASC)
  - Established in Palung (2016)
  - 3 in the process of establishment at Kalikot, Gorkha and Dhading

- ASCs will demonstrate the new technologies to the farmers and acts as the platform for training and research activities.
- LEE (Learning Experiential Exposure) program is initiated for B.Sc. Ag. and B.Sc. Forestry as a course requirement for last Semester. Prime Minister Agricultural Modernization Project (PMAMP) of Ministry of Agriculture Development is supporting this program by sending the students in Zones and Super-zones.
- Conducting Animal Health Camp, Plant clinics and IPM schools in the farmer's field, Installed Seed processing plant and is producing quality seeds to the farmers.
- The faculty members of the university focus their research works on increasing production and productivity of agricultural commodities, post-harvest technology, improving self-life of food products, biodiversity conservation, and local innovation adopting participatory approaches to enhance sustainable livelihood systems of farming communities.
- The postgraduate students are contributing thesis researches to generate knowledge and technologies to address the nationwide issues of agriculture, livestock and forestry.

### Curriculum Development Center

CDC is the constituent of Agriculture and Forestry University established under AFU Act section 18 enacted by Nepalese parliament in June, 2010. It is the part of academic affairs of university to provide academic excellence in teaching and direction to the academic program. CDC maintain academic quality of the university and provide the equivalence to the certificates given by the other universities of the globe.

#### CDC Operational Committee

There is an operational committee to provide policy and guidelines for the effective functioning of the CDC. The committee was formed as given in the rules book of AFU section 13.

- Chairman $\longrightarrow$ Chairman
- Faculty Deans $\longrightarrow$ Member
- Examination Controller $\longrightarrow$ Member
- Director, Continuing Education $\longrightarrow$ Member
- Chairman, Subject Matter Committee (3) $\longrightarrow$ Member
- Secretary, HSEB $\longrightarrow$ Member
- Director, CDC $\longrightarrow$ Secretary

#### Functions/Responsibility

- To develop curriculum of academic program of the university
- To update and revise the existing curriculum of the academic program according to changing needs of the consumer agencies and nation
- To publish text books, reference books and practical manuals to improve academic quality of the university
- To provide the equivalence to the certificates of the foreign university.

More than twenty certificates of different universities of the world have gained equivalence to the Agriculture and Forestry University academic courses.

### Directorate of planning

This directorate is responsible for short and long term plans and program budgets; monitors and evaluates the programs. It develops and Co-ordinates linkages with the national and international institutions in research, services and faculty development. It also recommends affiliation to other institutions and coordinate the affiliated institution. It also works as contact unit for line ministries and national government.

### Directorate of research and extension

Research and extension, besides teaching are mandatory functions at AFU as envisaged in its Act (2010). Considering this, Directorate of Research and Extension has been established at AFU. The main idea behind linking teaching to the research and extension are:

- to generate scientific information to help solve current problems in agriculture, including livestock and forestry;
- to establish research as mandatory function of university system so that it could contribute meaningfully to the development of agriculture, livestock and forestry sector in a holistic perspectives;
- to operate in a Land Grants model considering teaching, research and extension as tripartite and valuable components of the university system, and to strengthen university's teaching system through quality research and extension works also by linking its activities to the government's extension line agencies and research bodies.

### Institutional Review Board (IRB)

As the first and specialized technical university of Nepal, AFU aims to conduct teaching, research, and extension activities in the field of Agriculture, Livestock, Aquaculture, Forestry, and Socio-economics. Research, development, and innovation activities in all these sectors require formalization and alignment with international standards. Ethical issues in the aforementioned disciplines are serious, and fundamental issues related to customs and moral values of the public. Ethics relies on determining right and judicious activities and guided by moral principles existing in society. It is guided by the concept of human and animal right, social and professional responsibilities, and beyond. In social and biological researches, it is concerned with whether the activities proposed in the research is ethical or not. It is primarily concerned with safeguarding the interest of researchers and aims to promote their rights, dignity, values, and responsibilities. To address these issues, the AFU has developed Institutional Review Board (IRB) and its guidelines.

Recently, evaluation guidelines and Standard Operating Procedure (SOP) for for Non-Medical Human and Animal Subjects Research has been developed and implemented by the committee.

### Challenges and future direction

- Class rooms, farm buildings, laboratories, student dormitories and residential buildings need renovations.
- University needs support both for human resources and Infrastructure development from national and international section.
- Faculties and students require exposure on workings of universities at large to invest themselves in more meaningful learning, research and development works. This could be attained to some extent through student-faculty exchange programs.
